export default  {
      categories: [
        { id: '1', parent:'0', minimun: '25', title: 'Gastronomía' },
        { id: '2', parent:'0', minimun: '20', title: 'Indumentaria' },
        { id: '3', parent:'0', minimun: '25', title: 'Salud y cuidado personal' },
        { id: '4', parent:'0', minimun: '20', title: 'Servicios' },
        { id: '5', parent:'0', minimun: '15', title: 'Hogar ' },
        { id: '6', parent:'0', minimun: '10', title: 'Supermercado' },
        { id: '7', parent:'0', minimun: '10', title: 'Viajes y turismo' },
        { id: '8', parent:'0', minimun: '10', title: 'Construcción' },
        { id: '9', parent:'0', minimun: '10', title: 'Grandes comercios' },
        { id: '1', parent: '1', title: 'Restaurantes' },
        { id: '2', parent: '1', title: 'Fast Food' },
        { id: '3', parent: '1', title: 'Cervecerías' },
        { id: '4', parent: '1', title: 'Bar' },
        { id: '5', parent: '1', title: 'Otros' },
        { id: '1', parent: '2', title: 'Unisex' },
        { id: '2', parent: '2', title: 'Mujer' },
        { id: '5', parent: '2', title: 'Hombre' },
        { id: '6', parent: '2', title: 'Bebes & niños' },
        { id: '7', parent: '2', title: 'Calzado' },
        { id: '8', parent: '2', title: 'Marroquineria' },
        { id: '9', parent: '2', title: 'Otros' },
        { id: '1', parent: '3', title: 'SPA & Gimnasios' },
        { id: '2', parent: '3', title: 'Peluquerías' },
        { id: '3', parent: '3', title: 'Centros de estética' },
        { id: '4', parent: '3', title: 'Terapias alternativas' },
        { id: '5', parent: '3', title: 'Otros' },
        { id: '1', parent: '4', title: 'Educación' },
        { id: '2', parent: '4', title: 'Tecnología' },
        { id: '3', parent: '4', title: 'Comunicación' },
        { id: '4', parent: '4', title: 'Profesionales' },
        { id: '5', parent: '4', title: 'Otros' },
        { id: '1', parent: '5', title: 'Artículos del hogar' },
        { id: '2', parent: '5', title: 'Electro & Tecnología' },
        { id: '3', parent: '5', title: 'Jugueterías' },
        { id: '4', parent: '5', title: 'Colchones' },
        { id: '5', parent: '5', title: 'Otros' },
        { id: '1', parent: '6', title: 'Minorista' },
        { id: '2', parent: '6', title: 'Mayorista' },
        { id: '3', parent: '6', title: 'Otros' },
        { id: '1', parent: '7', title: 'Mayorista' },
        { id: '2', parent: '7', title: 'Minorista' },
        { id: '3', parent: '7', title: 'Otros' },
        { id: '1', parent: '8', title: 'Corralón' },
        { id: '2', parent: '8', title: 'Revestimientos' },
        { id: '3', parent: '8', title: 'Sanitarios & Grifería' },
        { id: '4', parent: '8', title: 'Electricidad' },
        { id: '5', parent: '8', title: 'Plomería' },
        { id: '6', parent: '8', title: 'Pintura' },
        { id: '7', parent: '8', title: 'Otros' },
        { id: '1', parent: '9', title: 'Mayorista' },
        { id: '2', parent: '9', title: 'Minorista' },
        { id: '3', parent: '9', title: 'Otros' },
      ]
    }

