export default  {
      categories: [
        { id: '1', parent:'0', minimun: '25', title: 'Gastronomía' },
        { id: '2', parent:'0', minimun: '20', title: 'Indumentaria' },
        { id: '3', parent:'0', minimun: '25', title: 'Salud y cuidado personal' },
        { id: '4', parent:'0', minimun: '20', title: 'Servicios' },
        { id: '5', parent:'0', minimun: '15', title: 'Hogar ' },
        { id: '6', parent:'0', minimun: '10', title: 'Supermercado' },
        { id: '7', parent:'0', minimun: '10', title: 'Viajes y turismo' },
        { id: '8', parent:'0', minimun: '10', title: 'Construcción' },
        { id: '9', parent:'0', minimun: '10', title: 'Grandes comercios' },
        { id: '1.1', parent: '1', title: 'Restaurantes' },
        { id: '1.2', parent: '1', title: 'Fast Food' },
        { id: '1.3', parent: '1', title: 'Cervecerías' },
        { id: '1.4', parent: '1', title: 'Bar' },
        { id: '1.5', parent: '1', title: 'Otros' },
        { id: '2.1', parent: '2', title: 'Unisex' },
        { id: '2.2', parent: '2', title: 'Mujer' },
        { id: '2.5', parent: '2', title: 'Hombre' },
        { id: '2.6', parent: '2', title: 'Bebes & niños' },
        { id: '2.7', parent: '2', title: 'Calzado' },
        { id: '2.8', parent: '2', title: 'Marroquineria' },
        { id: '2.9', parent: '2', title: 'Otros' },
        { id: '3.1', parent: '3', title: 'SPA & Gimnasios' },
        { id: '3.2', parent: '3', title: 'Peluquerías' },
        { id: '3.3', parent: '3', title: 'Centros de estética' },
        { id: '3.4', parent: '3', title: 'Terapias alternativas' },
        { id: '3.5', parent: '3', title: 'Otros' },
        { id: '4.1', parent: '4', title: 'Educación' },
        { id: '4.2', parent: '4', title: 'Tecnología' },
        { id: '4.3', parent: '4', title: 'Comunicación' },
        { id: '4.4', parent: '4', title: 'Profesionales' },
        { id: '4.5', parent: '4', title: 'Otros' },
        { id: '5.1', parent: '5', title: 'Artículos del hogar' },
        { id: '5.2', parent: '5', title: 'Electro & Tecnología' },
        { id: '5.3', parent: '5', title: 'Jugueterías' },
        { id: '5.4', parent: '5', title: 'Colchones' },
        { id: '5.5', parent: '5', title: 'Otros' },
        { id: '6.1', parent: '6', title: 'Minorista' },
        { id: '6.2', parent: '6', title: 'Mayorista' },
        { id: '6.3', parent: '6', title: 'Otros' },
        { id: '7.1', parent: '7', title: 'Mayorista' },
        { id: '7.2', parent: '7', title: 'Minorista' },
        { id: '7.3', parent: '7', title: 'Otros' },
        { id: '8.1', parent: '8', title: 'Corralón' },
        { id: '8.2', parent: '8', title: 'Revestimientos' },
        { id: '8.3', parent: '8', title: 'Sanitarios & Grifería' },
        { id: '8.4', parent: '8', title: 'Electricidad' },
        { id: '8.5', parent: '8', title: 'Plomería' },
        { id: '8.6', parent: '8', title: 'Pintura' },
        { id: '8.7', parent: '8', title: 'Otros' },
        { id: '9.1', parent: '9', title: 'Mayorista' },
        { id: '9.2', parent: '9', title: 'Minorista' },
        { id: '9.3', parent: '9', title: 'Otros' },
      ]
    }

